version: 2

jobs:
  build:
    docker:
      - image: maven:3.6-jdk-8-openj9
    steps:
      - checkout
      - run:
          name: Compute version number
          command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt

      - run:
          name: mvn package
          command: mvn package
