version: 2

jobs:
  prepare-dependencies:
    docker:
      - image: maven:3.6-jdk-8-openj9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-{{ arch }}-
      - run:
          name: mvn -U clean package verify
          command: mvn -U clean package verify

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ arch }}-{{ checksum "pom.xml" }}

      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    docker:
      - image: maven:3.6-jdk-8-openj9
    steps:
      - attach_workspace:
          at: .
      - run:
          name: mvn package
          command: mvn -U clean package verify


workflows:
  version: 2

  run:
    jobs:
      - prepare-dependencies
